---
dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  file_picker: ^8.3.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.1.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.4.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  photo_view: ^0.15.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  timeago: ^3.2.2
  zego_uikit: ^2.28.14
  zego_uikit_prebuilt_call: ^4.16.28
  zego_uikit_signaling_plugin: ^2.8.12
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: ^3.7.2
flutter:
  assets:
    - assets/svg/
  uses-material-design: true
name: flutter_chat_app
publish_to: none
version: 1.0.0+1
